#!/bin/sh

directory=$1
file_ext=$2
output_file=$3

files=`find $directory -name "*.$file_ext" | grep -v "src/vendor"`

echo "================ file auto generated by dump_code_to_file.sh ===============">$output_file
for file in $files 
do
	echo file: $file\n>>$output_file
	cat $file>>$output_file
done

